# Generated by Django 3.2 on 2021-05-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='')),
                ('importance', models.CharField(choices=[(1, 'very important'), (2, 'important'), (3, 'less important')], default='important', max_length=20)),
            ],
        ),
    ]
