# Generated by Django 3.2 on 2021-05-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='importance',
            field=models.CharField(choices=[('very important', 'very important'), ('important', 'important'), ('less important', 'less important')], default='less important', max_length=20),
        ),
    ]
