# Generated by Django 3.2 on 2021-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
